- name: Install Java
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Download Kafka
  get_url:
    url: https://downloads.apache.org/kafka/3.0.0/kafka_2.13-3.0.0.tgz
    dest: /opt/kafka.tgz

- name: Extract Kafka
  unarchive:
    src: /opt/kafka.tgz
    dest: /opt/
    remote_src: yes

- name: Start Kafka in background
  shell: nohup /opt/kafka_2.13-3.0.0/bin/kafka-server-start.sh /opt/kafka_2.13-3.0.0/config/server.properties &