- name: Install Java
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Download Elasticsearch
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.10.2-x86_64.rpm
    dest: /tmp/elasticsearch.rpm

- name: Install Elasticsearch
  yum:
    name: /tmp/elasticsearch.rpm
    state: present

- name: Enable and start Elasticsearch
  systemd:
    name: elasticsearch
    enabled: yes
    state: started